#ifndef __LUT_LIBRARY_LUT_INTERPOLATOR_INTERFACE__
#define __LUT_LIBRARY_LUT_INTERPOLATOR_INTERFACE__

#include "compute_mode.h"
#include "Lerp.hpp"

#endif // __LUT_LIBRARY_LUT_INTERPOLATOR_INTERFACE__
